# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
###################################################################
#####   CI ########################################################
- task: Docker@2
  inputs:
    containerRegistry: 'CN_POLYGLOT'
    repository: 'appdeposit'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      latest
      $(Build.BuildId)
###################################################################
#####   CD AKS DEPLOY #############################################
- task: replacetokens@5
  inputs:
    targetFiles: '**/*.yml'
    encoding: 'auto'
    tokenPattern: 'default'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Developer(a29dad22-fa1e-4b41-ace0-4159a70e3816)'
    azureResourceGroup: 'Devops'
    kubernetesCluster: 'polyglot-cluster-azure'
    useClusterAdmin: true
    command: 'apply'
    useConfigurationFile: true
    configuration: 'k8s-azure.yml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Developer(a29dad22-fa1e-4b41-ace0-4159a70e3816)'
    azureContainerRegistry: 'crpolyglot.azurecr.io'
    secretName: 'polyglot.com'
    versionSpec: 
    checkLatest: true